apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-aj65
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jxtq-tenant/rhtap-demo-app/hacbs-test-project-aj65@sha256:049cde28873581245602eef0093f56cfb2ab71e22743cf7859288afff04af86b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
