apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-aj65
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-aj65
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-aj65
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-aj65
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-aj65
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jxtq-tenant/rhtap-demo-app/hacbs-test-project-aj65@sha256:31e6f506cd9803ba3f6fdf97f9862b88fa84bcbafb80926c2fdf3b6f266cfc60
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
